name: Build and Package Application

on: [push]

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-11, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install uvloop

    - name: Build macOS Application
      run: |
        python file-watcher/setup.py py2app
        zip -r "file-watcher/dist/Quick Embed.app.zip" "file-watcher/dist/Quick Embed.app"

    - name: Upload macOS Application
      uses: actions/upload-artifact@v2
      with:
        name: Quick-Embed-macOS-${{ matrix.os }}
        path: file-watcher/dist/"Quick Embed.app.zip"

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Windows Application
      run: |
        pyinstaller --onefile --windowed --icon=file-watcher/icon.ico --name "Quick Embed" file-watcher/app.py

    - name: Zip Windows Application
      run: |
        zip -r "Quick Embed.zip" "file-watcher/dist/Quick Embed.exe"

    - name: Upload Windows Application
      uses: actions/upload-artifact@v2
      with:
        name: Quick-Embed-Windows
        path: Quick Embed.zip
