name: Build and Package Application

on: [push]

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-11, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install uvloop
        pip install py2app

    - name: Build macOS Application
      run: |
        python file-watcher/setup.py py2app

    - name: Upload macOS Application
      uses: actions/upload-artifact@v2
      with:
        name: Quick-Embed-macOS-${{ matrix.os }}
        path: dist/Quick Embed.app

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Windows Application
      run: |
        pyinstaller --onefile --windowed --icon=file-watcher/icon.ico --name "Quick Embed" file-watcher/app.py


    - name: Upload Windows Application
      uses: actions/upload-artifact@v2
      with:
        name: Quick-Embed-Windows
        path: dist/Quick Embed.exe

  create-release:
    needs: [ build-macos, build-windows ]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload macOS Application Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Quick Embed.app
          asset_name: Quick-Embed-macOS-${{ matrix.os }}.zip
          asset_content_type: application/zip

      - name: Upload Windows Application Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Quick Embed.exe
          asset_name: Quick-Embed-Windows.zip
          asset_content_type: application/zip

